/**
 * @fileoverview Console Utilities - Development and Production Console Management
 * 
 * This utility provides functions to manage console output based on environment
 * and suppress unnecessary warnings in production while maintaining useful
 * development information. It includes:
 * - Production warning suppression
 * - Enhanced error logging with context
 * - Development-only logging utilities
 * - Performance monitoring helpers
 * 
 * @author Alvi Global Enterprises
 * @version 1.0.0
 */

/**
 * Suppresses specific, known console warnings during development to reduce noise.
 *
 * This function "monkey-patches" the global `console` and `window` error handlers to intercept
 * and filter out warnings that are expected and harmless, such as those generated by the
 * Spline 3D background library or React DevTools. It should be called once at application startup.
 * In production, this function has no effect on `console.warn` and `console.log`.
 *
 * @returns {void} This function does not return a value.
 */
export const suppressConsoleWarnings = () => {
  // Store original console functions
  const originalWarn = console.warn;
  const originalLog = console.log;
  const originalError = console.error;
  
  // Store original window error handlers
  const originalWindowError = window.onerror;
  const originalWindowUnhandledRejection = window.onunhandledrejection;
  
  // Add user-friendly console message about expected warnings
  if (import.meta.env.DEV) {
    setTimeout(() => {
      originalLog('%c🎨 Spline 3D Background Active', 'color: hsl(var(--resolution-blue-600)); font-weight: bold; font-size: 14px;');
      originalLog('%cℹ️ Some WebGL and iframe warnings are expected and can be safely ignored.', 'color: hsl(var(--muted-foreground)); font-size: 12px;');
      originalLog('%cThese warnings come from the 3D animation system and do not affect functionality.', 'color: hsl(var(--muted-foreground)); font-size: 12px;');
    }, 1000);
  }
  
  // Helper function to check if message should be suppressed
  // Only suppress known, harmless warnings - be conservative to avoid hiding real issues
  const shouldSuppress = (message: unknown): boolean => {
    if (typeof message === 'string') {
      const messageStr = message.toLowerCase();
      return (
        // React development warnings that are informational only
        messageStr.includes('react router future flag warning') ||
        messageStr.includes('download the react devtools') ||
        messageStr.includes('reactjs.org/link/react-devtools') ||
        messageStr.includes('react does not recognize the `allowtransparency` prop') ||
        
        // Browser intervention warnings that are informational
        messageStr.includes('[intervention] images loaded lazily') ||
        messageStr.includes('load events are deferred') ||
        
        // WebGL framebuffer warnings from Spline 3D background
        messageStr.includes('gl_invalid_framebuffer_operation') ||
        (messageStr.includes('framebuffer') && messageStr.includes('incomplete')) ||
        (messageStr.includes('framebuffer') && messageStr.includes('attachment has zero size')) ||
        (messageStr.includes('webgl') && messageStr.includes('glclear')) ||
        (messageStr.includes('webgl') && messageStr.includes('gldrawelements')) ||
        (messageStr.includes('webgl') && messageStr.includes('glclearbuffer')) ||
        
        // iframe sandbox warnings from Spline
        (messageStr.includes('iframe') && messageStr.includes('sandbox') && messageStr.includes('escape')) ||
        (messageStr.includes('iframe') && messageStr.includes('allow-scripts') && messageStr.includes('allow-same-origin'))
      );
    }
    return false;
  };
  
  // Override console.warn with filtered version
  console.warn = (...args: unknown[]) => {
    // Only log in development mode
    if (import.meta.env.DEV) {
      if (shouldSuppress(args[0])) {
        return; // Suppress these warnings
      }
      originalWarn.apply(console, args);
    }
  };
  
  // Override console.log with filtered version (for development messages)
  console.log = (...args: unknown[]) => {
    // Only log in development mode
    if (import.meta.env.DEV) {
      if (shouldSuppress(args[0])) {
        return; // Suppress these development messages
      }
      originalLog.apply(console, args);
    }
  };
  
  // Override console.error with filtered version (for React warnings)
  console.error = (...args: unknown[]) => {
    // Always log errors, but filter in development
    if (import.meta.env.DEV && shouldSuppress(args[0])) {
      return; // Suppress these React warnings in development
    }
    originalError.apply(console, args);
  };
  
  // Override window error handlers to suppress WebGL and iframe warnings
  window.onerror = (message, source, lineno, colno, error) => {
    const errorMessage = String(message);
    if (shouldSuppress(errorMessage)) {
      return true; // Suppress the error
    }
    if (originalWindowError) {
      return originalWindowError.call(window, message, source, lineno, colno, error);
    }
    return false;
  };
  
  window.onunhandledrejection = (event) => {
    const reason = String(event.reason);
    if (shouldSuppress(reason)) {
      event.preventDefault();
      return;
    }
    if (originalWindowUnhandledRejection) {
      originalWindowUnhandledRejection.call(window, event);
    }
  };
  
  // Ensure console methods are properly overridden on window object
  if (typeof window !== 'undefined') {
    (window as Window & { console: typeof console }).console = {
      ...console,
      warn: console.warn,
      log: console.log,
      error: console.error
    };
  }
};

/**
 * Logs an error to the console with additional context, but only in the development environment.
 * In production, this function does nothing, preventing sensitive error details from being
 * exposed to end-users. It formats the output in a collapsible group for readability.
 *
 * @param {string} context - A string describing the context in which the error occurred (e.g., "API Fetch", "Component Render").
 * @param {unknown} error - The error object or value that was caught.
 * @param {Record<string, unknown>} [additionalInfo] - Optional. An object containing additional data to be logged alongside the error.
 * @returns {void} This function does not return a value.
 */
export const logError = (context: string, error: unknown, additionalInfo?: Record<string, unknown>) => {
  if (import.meta.env.DEV) {
    // Development: Detailed error logging with grouping
    console.group(`🚨 Error in ${context}`);
    console.error('Error:', error);
    if (additionalInfo) {
      console.info('Additional Info:', additionalInfo);
    }
    console.groupEnd();
  } else {
    // Production: No console logging for security and performance
    // In production, errors should be sent to monitoring services
    // Example: errorReportingService.captureException(error, { context, additionalInfo });
  }
};

/**
 * Logs a message and optional data to the console, but only in the development environment.
 * This utility is automatically stripped from production builds, making it safe to use
 * for debugging without affecting performance.
 *
 * @param {string} message - The primary message to be logged.
 * @param {unknown} [data] - Optional. Additional data to be logged along with the message.
 * @returns {void} This function does not return a value.
 */
export const devLog = (message: string, data?: unknown) => {
  if (import.meta.env.DEV) {
    console.log(`🔧 ${message}`, data || '');
  }
  // Production: No logging for performance and security
};

/**
 * A utility for logging performance measurements to the console in the development environment.
 * It calculates the duration between a start time and the current time and logs it with a descriptive label.
 * This function is stripped from production builds.
 *
 * @param {string} label - A descriptive label for the performance measurement (e.g., "Data Processing").
 * @param {number} startTime - The starting timestamp, usually obtained from `performance.now()`.
 * @returns {void} This function does not return a value.
 */
export const perfLog = (label: string, startTime: number) => {
  if (import.meta.env.DEV) {
    const duration = performance.now() - startTime;
    console.log(`⏱️ ${label}: ${duration.toFixed(2)}ms`);
  }
  // Production: No logging for performance and security
};

/**
 * Blurs the currently active DOM element.
 *
 * This utility is useful for managing focus, especially before opening a modal or dialog.
 * Blurring the active element can prevent accessibility issues where focus might be trapped
 * in an element that is about to be hidden by an overlay.
 *
 * @returns {void} This function does not return a value.
 */
export const blurActiveElement = () => {
  const activeElement = document.activeElement;
  if (activeElement && activeElement instanceof HTMLElement) {
    activeElement.blur();
  }
};
