/**
 * @fileoverview TypeScript Type Definitions for Google Gemini AI API
 * 
 * Provides comprehensive type definitions for interacting with the Google Gemini AI API.
 * These types ensure type safety and enable IntelliSense for requests and responses,
 * improving developer experience and reducing runtime errors.
 * 
 * @module types/gemini
 * @author Alvi Global Enterprises
 * @version 1.0.0
 */

/**
 * Defines the structure for a single piece of content sent to or received from the Gemini API.
 * It consists of one or more text parts.
 *
 * @interface GeminiContent
 * @property {object[]} parts - An array of content parts.
 * @property {string} parts.text - The text content of a part.
 */
export interface GeminiContent {
  /** Array of content parts, each containing text. */
  parts: {
    /** The actual text content to be processed by the model. */
    text: string;
  }[];
}

/**
 * Defines the structure for a request sent to the Gemini API's `generateContent` endpoint.
 *
 * @interface GeminiRequest
 * @property {GeminiContent[]} contents - An array of content objects that form the prompt for the AI model.
 */
export interface GeminiRequest {
  /** An array of content objects that make up the prompt sent to the AI model. */
  contents: GeminiContent[];
}

/**
 * Defines the structure of a successful response from the Gemini API.
 * It includes the generated content candidates and metadata about the generation process.
 *
 * @interface GeminiResponse
 * @property {object[]} candidates - An array of potential responses generated by the model.
 * @property {GeminiContent} candidates.content - The generated content for a candidate.
 * @property {string} candidates.finishReason - The reason the model stopped generating content (e.g., "STOP", "MAX_TOKENS").
 * @property {number} candidates.index - The index of the candidate in the response array.
 * @property {object[]} candidates.safetyRatings - An array of safety ratings for the generated content.
 * @property {string} candidates.safetyRatings.category - The category of the safety concern (e.g., "HARM_CATEGORY_HARASSMENT").
 * @property {string} candidates.safetyRatings.probability - The likelihood of the content falling into the safety category (e.g., "NEGLIGIBLE").
 * @property {object} promptFeedback - Feedback on the input prompt provided in the request.
 * @property {object[]} promptFeedback.safetyRatings - Safety ratings for the input prompt itself.
 */
export interface GeminiResponse {
  /** An array of generated content candidates from the model. */
  candidates: {
    /** The content generated by the model for this candidate. */
    content: GeminiContent;
    /** The reason the model stopped generating content (e.g., "STOP"). */
    finishReason: string;
    /** The index of this candidate in the list of responses. */
    index: number;
    /** Safety ratings for the generated content of this candidate. */
    safetyRatings: {
      /** The category of the safety concern (e.g., "HARM_CATEGORY_HARASSMENT"). */
      category: string;
      /** The assessed probability of the content belonging to the category (e.g., "NEGLIGIBLE"). */
      probability: string;
    }[];
  }[];
  /** Feedback regarding the safety of the input prompt. */
  promptFeedback: {
    /** Safety ratings for the prompt provided in the request. */
    safetyRatings: {
      /** The category of the safety concern. */
      category: string;
      /** The assessed probability of the prompt belonging to the category. */
      probability: string;
    }[];
  };
}